name:                AOC2022
version:             0.1.0.0
github:              "b1g3ar5/AOC2022"
license:             BSD3
author:              "Nick Straw"
maintainer:          "nick@broxholme.com"
copyright:           "N J Straw"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Personal

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/b1g3ar5/AOC2022#readme>

dependencies:
- base >= 4.7 && < 5
- timeit
- MissingH
- split
- containers
- unordered-containers
- hashable
- vector
- recursion-schemes
- array
- mtl
- search-algorithms
- parallel
- data-fix
- recursion

default-extensions: GHC2021

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  AOC2022-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AOC2022

tests:
  AOC2022-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AOC2022
