resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/19/33.yaml

packages:
- .

default-extensions: GHC2021

# extra-deps:
# - acme-missiles-0.3
# - git: https://github.com/commercialhaskell/stack.git
#   commit: e7b331f14bcffb8367cd58fbfc8b40ec7642100a
#
# extra-deps: []

system-ghc: true

# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
#
